title = "gitleaks config"

[[rules]]
        description = "AWS Manager ID"
        regex = '''(A3T[A-Z0-9]|AKIA|AGPA|AIDA|AROA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}'''
        tags = ["key", "AWS"]
[[rules]]
        description = "AWS Secret Key"
        regex = '''(?i)aws(.{0,20})?(?-i)['\"][0-9a-zA-Z\/+]{40}['\"]'''
        tags = ["key", "AWS"]
[[rules]]
        description = "AWS MWS key"
        regex = '''amzn\.mws\.[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}'''
        tags = ["key", "AWS", "MWS"]
[[rules]]
        description = "Facebook Secret Key"
        regex = '''(?i)(facebook|fb)(.{0,20})?(?-i)['\"][0-9a-f]{32}['\"]'''
        tags = ["key", "Facebook"]
[[rules]]
        description = "Facebook Client ID"
        regex = '''(?i)(facebook|fb)(.{0,20})?['\"][0-9]{13,17}['\"]'''
        tags = ["key", "Facebook"]
[[rules]]
        description = "Twitter Secret Key"
        regex = '''(?i)twitter(.{0,20})?['\"][0-9a-z]{35,44}['\"]'''
        tags = ["key", "Twitter"]
[[rules]]
        description = "Twitter Client ID"
        regex = '''(?i)twitter(.{0,20})?['\"][0-9a-z]{18,25}['\"]'''
        tags = ["client", "Twitter"]
        [rules.allowlist]
                description = "ignore example account names"
                regexes = ['''(?i)(twitter.*)=\s*(")[a-z]*(")''']
[[rules]]
        description = "Github"
        regex = '''(?i)github(.{0,20})?(?-i)['\"][0-9a-zA-Z]{35,40}['\"]'''
        tags = ["key", "Github"]
[[rules]]
        description = "LinkedIn Client ID"
        regex = '''(?i)linkedin(.{0,20})?(?-i)['\"][0-9a-z]{12}['\"]'''
        tags = ["client", "LinkedIn"]
[[rules]]
        description = "LinkedIn Secret Key"
        regex = '''(?i)linkedin(.{0,20})?['\"][0-9a-z]{16}['\"]'''
        tags = ["secret", "LinkedIn"]
[[rules]]
        description = "Slack"
        regex = '''xox[baprs]-([0-9a-zA-Z]{10,48})?'''
        tags = ["key", "Slack"]
[[rules]]
        description = "Asymmetric Private Key"
        regex = '''-----BEGIN ((EC|PGP|DSA|RSA|OPENSSH) )?PRIVATE KEY( BLOCK)?-----'''
        tags = ["key", "AsymmetricPrivateKey"]
#[[rules]]
    #    description = "Generic Credential"
      #  regex = '''(?i)(api_key|apikey|secret)(.{0,20})?['|"][0-9a-zA-Z]{16,45}['|"]'''
      #  tags = ["key", "API", "generic"]
# Modified
[[rules]]
        description = "Google API key"
        #regex = '''AIza[0-9A-Za-z\\-_]{35}'''
        regex = '''AIza[0-9A-Za-z\\\-\_]{35}'''
        tags = ["key", "Google"]
[[rules]]
        description = "Heroku API key"
        regex = '''(?i)heroku(.{0,20})?['"][0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}['"]'''
        tags = ["key", "Heroku"]
[[rules]]
        description = "MailChimp API key"
        regex = '''(?i)(mailchimp|mc)(.{0,20})?['"][0-9a-f]{32}-us[0-9]{1,2}['"]'''
        tags = ["key", "Mailchimp"]
[[rules]]
        description = "Mailgun API key"
        regex = '''(?i)(mailgun|mg)(.{0,20})?['"][0-9a-z]{32}['"]'''
        tags = ["key", "Mailgun"]
[[rules]]
        description = "PayPal Braintree access token"
        regex = '''access_token\$production\$[0-9a-z]{16}\$[0-9a-f]{32}'''
        tags = ["key", "Paypal"]
[[rules]]
        description = "Picatic API key"
        regex = '''sk_live_[0-9a-z]{32}'''
        tags = ["key", "Picatic"]
[[rules]]
        description = "SendGrid API Key"
        regex = '''SG\.[\w_]{16,32}\.[\w_]{16,64}'''
        tags = ["key", "SendGrid"]
[[rules]]
        description = "Slack Webhook"
        regex = '''https://hooks.slack.com/services/T[a-zA-Z0-9_]{8}/B[a-zA-Z0-9_]{8}/[a-zA-Z0-9_]{24}'''
        tags = ["key", "slack"]
[[rules]]
        description = "Stripe API key"
        regex = '''(?i)stripe(.{0,20})?['\"][sk|rk]_live_[0-9a-zA-Z]{24}'''
        tags = ["key", "Stripe"]
[[rules]]
        description = "Square access token"
        regex = '''sq0atp-[0-9A-Za-z\-_]{22}'''
        tags = ["key", "square"]
[[rules]]
        description = "Square OAuth secret"
        regex = '''sq0csp-[0-9A-Za-z\\-_]{43}'''
        tags = ["key", "square"]
[[rules]]
        description = "Twilio API key"
        regex = '''(?i)twilio(.{0,20})?['\"][0-9a-f]{32}['\"]'''
        tags = ["key", "twilio"]


# ========== My Rules ==========
# 10 Rules Introduced by Mindtree

[[rules]]
        description = "Azure Storage Account Access Key"
        #regex = '''(?i)(DefaultEndpointsProtocol|AccountName|AccountKey|EndpointSuffix)\s*=\s*(.*){0,127}'''
        regex = '''(?i)((DefaultEndpointsProtocol)\s*=\s*(.*);(AccountName)\s*=\s*(.*);(AccountKey)\s*=\s*(.*);(EndpointSuffix)\s*=\s*(.*))|(Endpoint=.*;AccountKey=.*)'''
        tags = ["key", "Azure", "Storage Account"]
        [rules.allowlist]
                description = "ignore example account names"
                regexes = ['''(?i)(AccountName)\s*(=|:)\s*((.*Name)|true|false|config\[.*\])''',
                           '''(?i)(AccountKey)\s*(=|:)\s*(config\[.*\])''',
                           '''.*\=\s*\(\.\*\)'''
                        ]
        
# 31 out of 31

[[rules]]
        description = "Azure Service Bus SharedAccessSignature / SharedAccessKey / WebHookToken"
        regex = '''(?i)(Endpoint(=(\s*)sb:\/*)|SharedAccessKeyName|SharedAccessKey)\s*=+\s*(.*){0,127}'''
        tags = ["key", "Azure", "Storage Account"]
# 131 out of 131

[[rules]]
        description = "Azure Function Master/API Key"
        regex = '''(?i)(https:\/{2})[a-zA-Z0-9-._]*(.azurewebsites.net\/api\/)[a-zA-Z0-9]*\?(code)=(\w|\W)*'''
        tags = ["key", "Azure", "Function", "Master", "API"]
# 3 out of 3

[[rules]]
        description = "Azure Storage Account Shared Access Signature"
        regex = '''(\\?sv=[0-9]{4}-[0-9]{2}-[0-9]{2}&{1})[\w\W]*'''
        tags = ["key", "Azure", "Storage Account"]
# 2 out of 2

[[rules]]
        description = "Azure Client Secret, Access token and Api Key"
        regex = '''("|')?(?i)(client.?secret|ClientKey|accessToken|ApiKey)("|')?\s*(:|=)\s*("|')[^|\s]([\w-]+)("|')'''
        tags = ["Azure", "API", "client secret", "Access token"]
        [rules.allowlist]
                description = "ignore example access tokens and api keys"
                regexes = ['''(?i)(("|')?(ApiKey)("|')?\s*(:|=)\s*("|')([a-zA-Z]*apikey)("|'))|(("|')?(accessToken)("|')?\s*(:|=)\s*("|')([a-zA-Z]*access.?token)("|'))|((?i)("|')?(secret|client_secret)("|')?\s*(:|=)\s*("|')([a-zA-Z]*ClientSecret)("|'))''',
                           '''("|')take\_from\_kv("|')''',
                           '''(")your\-service\-principal\-client\-secret(")'''
                        ]
                
# 41 out of 25

[[rules]]
        description = "Azure SQL Connection String"
        regex = '''(?i)(("|')?(Server|Data Source|url)=(.*);\s*(Database|Initial Catalog)=(.*);\s*(Integrated Security=(False|True);)?\s*(UID|User ID|Username|user)=(.*);\s*(Password|Pwd)=(.*)("|')?)|(("|')?(UID|User ID|Username|user)=(.*);\s*(Password|Pwd)=(.*);\s*(Server|Data Source|url)=(.*);\s*(Database|Initial Catalog)=(.*)("|')?)'''
        tags = ["key", "Azure", "SQL Connection String"]
        [rules.allowlist]
                description = "ignore example access tokens"
                regexes = ['''(?i)("|')?(UID|User ID|Username|user)=(.*);(Password|Pwd)=(.*password|.*parameters.*);(Server|Data Source|url)=(.*ServerName);(Database|Initial Catalog)=(.*db)("|')?''']
# 138 out of 138

[[rules]]
        description = "AccessToken"
        regex = '''("|')?(?i)(accessToken|ACCESS_TOKEN)("|')?\s*(:|\|\|)\s*("|')\s?[\w-]+("|')'''
        tags = ["accessToken", "ACCESS_TOKEN"]
        [rules.allowlist]
                description = "ignore example access tokens"
                regexes = ['''("|')?(?i)(accessToken|ACCESS_TOKEN)("|')?\s*(:|\|\|)\s*("|')([a-zA-Z]*access.?token)("|')''']

[[rules]]
        description = "OcpApimSubscriptionKey, x-functions-key and passkey"
        regex = '''("|')(?i)(OcpApimSubscriptionKey|passkey|x-functions-key)("|')\s*:\s*("|')[a-zA-Z0-9\-\/\=]*("|')'''
        tags = ["OcpApimSubscriptionKey", "passkey"]

[[rules]]
        description = "JWT secret and Client secret"
        regex = '''("|')?(?i)(secret|client_secret)("|')?\s*(:|=)\s*("|')[\w\?\:\;\@\`\<\>\[\]\\\/\.\$\-\s\=\!\+\(\)\*\|\^\{\}\&]+("|')'''
        tags = ["flip.security", "jwt", "secret", "client_credentials", "client_secret"]
        [rules.allowlist]
                description = "ignore example secrets"
                regexes = ['''(\'secret\smust\sbe\sa\sstring\sor\sbuffer\')|(SECRET\_DO\_NOT\_PASS\_THIS\_OR\_YOU\_WILL\_BE\_FIRED)|('YOUR_DIRECT_LINE_SECRET')|((?i)("|')?(secret|client_secret)("|')?\s*(:|=)\s*("|')(.*secret.*)("|'))''']
                #|(("|')?secret("|')?\s*(:|=)\s*("|')(.*secret)("|'))

[[rules]]
        description = "Generic password"
        regex = '''("|')?(?i)(default.password|password|userPWD)("|')?\s*(:|=){1,3}\s*("|')[a-zA-Z0-9ñ\@\#\$\%\^\&\-\+\=\(\)\/\.\_\<\;\:\>\\\!\[\]\?\{\}\|\*]+("|')'''
        tags = ["password"]
        [rules.allowlist]
                description = "ignore example password"
                regexes = ['''(?i)("|')?password("|')?\s*(:|=)+\s*((\'text\')|(\'string\')|(("|').*password("|'))|(("|')take\_from\_kv("|'))|(true)|(false)|("|').*\.cshtml("|'))''']

[[rules]]
        description = "Generic password in key-value pairs"
        regex = '''(name|key)(=").*(p|P)assword(").*(value=")[a-zA-Z0-9ñ\@\#\$\%\^\&\-\+\=\(\)\/\.\_\<\;\:\>\\\!\[\]\?\{\}\|\*]+(")'''
        tags = ["password", "name", "value"]
        [rules.allowlist]
                description = "ignore example password"
                regexes = ['''(?i)(value=")((\'text\')|(\'string\')|(.*password(\])?)|(take\_from\_kv)|(true)|(false)|(forgotpwd))''']

[[rules]]
        description = "Keys in key-value pairs"
        regex = '''(name|key)(=").*(k|K)ey(").*(value=")([\w-]+)(")'''
        tags = ["key", "name", "value"]
        [rules.allowlist]
                description = "ignore example keys"
                regexes = ['''(?i)(value=")(.*Id|.*secret|.*group|.*name|.*authority.*|.*key|.*url|.*pipeline|.*servicebus|.*container|.*connectionstring|.*Hierarchy|other|deactive|[a-z\-]+|YOUR_ENCRYPTION_KEY_TO_GO_HERE)(")''']

[[rules]]
        description = "Secrets in key-value pairs"
        regex = '''(name|key)(=").*(s|S)ecret(e)?(").*(value=")[\w\?\:\;\@\`\<\>\[\]\\\/\.\$\-\s\=\!\+\(\)\*\|\^\{\}\&]+(")'''
        tags = ["secret", "name", "value"]
        [rules.allowlist]
                description = "ignore example secrets"
                regexes = ['''(?i)(value=")(.*secret.*)(")''']

[[rules]]
        description = "Mongo DB Connection String"
        regex = '''(?i)(")ConnectionString("):\s*(")mongodb:\/\/(.*)(")'''
        tags = ["mongodb", "ConnectionString"]

[allowlist]
        paths = [
                '''.*\.item''',
                '''.*urls\.css''',
                '''PG\.SKII\.Environments\/(DEV\-CD|DEV\-CM|INT\-CD|INT\-CM|Load\-CD|Load\-CM|SIT\-CD|SIT\-CM)\/Web.config'''
        ]
